
                (function() {
                    var nodeEnv = typeof require !== 'undefined' && typeof process !== 'undefined';
                    var __module = nodeEnv ? module : {exports:{}};
                    var __filename = 'preview-scripts/__qc_index__.js';
                    var __require = nodeEnv ? function (request) {
                        return cc.require(request);
                    } : function (request) {
                        return __quick_compile_project__.require(request, __filename);
                    };
                    function __define (exports, require, module) {
                        if (!nodeEnv) {__quick_compile_project__.registerModule(__filename, module);}
require('./assets/scripts/AndroidManager');
require('./assets/scripts/Appcfg');
require('./assets/scripts/ArgsParseUtils');
require('./assets/scripts/AudioMgr');
require('./assets/scripts/BaseButton');
require('./assets/scripts/BaseCtrl');
require('./assets/scripts/BaseData');
require('./assets/scripts/BaseMgr');
require('./assets/scripts/BasePlatform');
require('./assets/scripts/BaseUI');
require('./assets/scripts/ByteDanceManager');
require('./assets/scripts/CacheUtils');
require('./assets/scripts/CameraMgr');
require('./assets/scripts/CardMgr');
require('./assets/scripts/CityMgr');
require('./assets/scripts/ComCollectionData');
require('./assets/scripts/ComDataMgr');
require('./assets/scripts/ComFreeTimeData');
require('./assets/scripts/ComGameData');
require('./assets/scripts/ComLottyData');
require('./assets/scripts/ComPlayerMgr');
require('./assets/scripts/ComSignData');
require('./assets/scripts/CommonBirge');
require('./assets/scripts/CommonCfg');
require('./assets/scripts/CommonModel');
require('./assets/scripts/Config');
require('./assets/scripts/DataMgr');
require('./assets/scripts/EditorManager');
require('./assets/scripts/EffectMgr');
require('./assets/scripts/EquipMgr');
require('./assets/scripts/EventMgr');
require('./assets/scripts/FetterMgr');
require('./assets/scripts/GameData');
require('./assets/scripts/GameDataMgr');
require('./assets/scripts/GameMgr');
require('./assets/scripts/GoodsManager');
require('./assets/scripts/GuideData');
require('./assets/scripts/HttpMgr');
require('./assets/scripts/IosManager');
require('./assets/scripts/KSManager');
require('./assets/scripts/LabPlatform');
require('./assets/scripts/LabelPlus');
require('./assets/scripts/LadleWordMgr');
require('./assets/scripts/LanguageMgr');
require('./assets/scripts/List');
require('./assets/scripts/ListItem');
require('./assets/scripts/Loading');
require('./assets/scripts/LogMgr');
require('./assets/scripts/Main');
require('./assets/scripts/MainTaskData');
require('./assets/scripts/Monster');
require('./assets/scripts/MysticalShopData');
require('./assets/scripts/NodeCurrency');
require('./assets/scripts/NodeDropGoods');
require('./assets/scripts/NodeEquip');
require('./assets/scripts/NodeEquipComposite');
require('./assets/scripts/NodeFetter');
require('./assets/scripts/NodeMainTask');
require('./assets/scripts/NodeSkill');
require('./assets/scripts/NodeSkillBook');
require('./assets/scripts/NodeTask');
require('./assets/scripts/NodeUISkillBook');
require('./assets/scripts/NodeUISkillBookNew');
require('./assets/scripts/NodeWearEquip');
require('./assets/scripts/ObjectMgr');
require('./assets/scripts/ObjectsParent');
require('./assets/scripts/OppoManager');
require('./assets/scripts/PetMgr');
require('./assets/scripts/PlatformManager');
require('./assets/scripts/Player');
require('./assets/scripts/PlayerMgr');
require('./assets/scripts/PoolMgr');
require('./assets/scripts/RedDotMgr');
require('./assets/scripts/ResCacheMgr');
require('./assets/scripts/ResourceMgr');
require('./assets/scripts/RoleMgr');
require('./assets/scripts/ScrollCard');
require('./assets/scripts/SdkMgr');
require('./assets/scripts/ShareData');
require('./assets/scripts/SkillMgr');
require('./assets/scripts/SpineUtils');
require('./assets/scripts/TaskMgr');
require('./assets/scripts/TimeMgr');
require('./assets/scripts/TimeUtils');
require('./assets/scripts/TipsMgr');
require('./assets/scripts/TrackData');
require('./assets/scripts/TrackDataEvent');
require('./assets/scripts/TranstaLabel');
require('./assets/scripts/TranstanImg');
require('./assets/scripts/TweenMgr');
require('./assets/scripts/UIBecoming');
require('./assets/scripts/UICollection');
require('./assets/scripts/UICompositeEnd');
require('./assets/scripts/UIDrawCard');
require('./assets/scripts/UIEquip');
require('./assets/scripts/UIEquipComposite');
require('./assets/scripts/UIEquipInfo');
require('./assets/scripts/UIExit');
require('./assets/scripts/UIFastPass');
require('./assets/scripts/UIFetterInfo');
require('./assets/scripts/UIFreeTime');
require('./assets/scripts/UIGame');
require('./assets/scripts/UIGeneralWindow');
require('./assets/scripts/UIGeneralWindow1');
require('./assets/scripts/UIGuide');
require('./assets/scripts/UIHome');
require('./assets/scripts/UILotty');
require('./assets/scripts/UIMainTask');
require('./assets/scripts/UIMgr');
require('./assets/scripts/UIMysticalShop');
require('./assets/scripts/UINotBagIndex');
require('./assets/scripts/UIOnlineReward');
require('./assets/scripts/UIPause');
require('./assets/scripts/UIPet');
require('./assets/scripts/UIRealName');
require('./assets/scripts/UIReward');
require('./assets/scripts/UISalutation');
require('./assets/scripts/UISellView');
require('./assets/scripts/UISetting');
require('./assets/scripts/UISettle');
require('./assets/scripts/UIShareVideo');
require('./assets/scripts/UIShop');
require('./assets/scripts/UISign');
require('./assets/scripts/UISkillBook');
require('./assets/scripts/UISkillBookInfo');
require('./assets/scripts/UISkillInfo');
require('./assets/scripts/UITask');
require('./assets/scripts/UITips');
require('./assets/scripts/UITop');
require('./assets/scripts/UITouch');
require('./assets/scripts/UIUtils');
require('./assets/scripts/UserData');
require('./assets/scripts/Utils');
require('./assets/scripts/VivoManager');
require('./assets/scripts/Weapon');
require('./assets/scripts/WebLinkManager');
require('./assets/scripts/WechatManager');

                    }
                    if (nodeEnv) {
                        __define(__module.exports, __require, __module);
                    }
                    else {
                        __quick_compile_project__.registerModuleFunc(__filename, function () {
                            __define(__module.exports, __require, __module);
                        });
                    }
                })();